site_name: FDCA
site_url: https://kasperhk.github.io/fdca-web

#structure
nav:
        - Hjem: index.md
        - Om FDCA: news.md
        - Vores medlemmer: osint_tools.md
        - 'Cheat sheets':
          - 'Git Cheat sheet': 'cheat_sheets/git_cheat_sheet.md'
        - Cyberværnepligten:
          - 'Network Security':
            - 'Week 07': 'exercises/network_security/exercises_ww07.md'

#theme
theme: 
  name: material

  features:
    - navigation.tabs

  palette:
    - scheme: default
      primary: blue grey
      accent: deep purple
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: blue grey
      accent: red
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/images/favicon.png
  icon:
    logo: /assets/images/fdca

